### PR TITLE
Latency rework

### PR DESCRIPTION
**Pull request by jakobilobi**
Basically working, but not planning to push to prod Friday afternoon. No matter what Gustav says ;)

Will merge early next week, after some more cleanup. You're welcome to review if you'd like to but not necessary!

### CODE REVIEW

**Review by erik78se — APPROVED** [review]
Looks good to me.

**Comment by erik78se** [comment]
Whats the reason for going to 12 connection in the concurrency ?

**Comment by jakobilobi** [comment]
> Whats the reason for going to 12 connection in the concurrency ?

This is WIP, numbers not final. Have been testing a bit for what numbers that give the best results.

**Comment by jakobilobi** [comment]
> Whats the reason for going to 12 connection in the concurrency ?

Out of curiosity, how many would you expect?

The reason to use concurrency at all is to make it faster, make it parse the entire list of RPC endpoints as fast as possible while not affecting the latency measurements.

It's set to 8 now, which is probably a decent level to have it at.

**Comment by jakobilobi** [comment]
I'll be merging this now. It's in prod and working fine. Further updates will end up on `main`!

**Pull request merged**
